### ISSUE TITLE
Implement JTAG support

### ISSUE THREAD

**Issue by Disasm** [probe-rs/hs-probe-firmware#10]

**Comment by adamgreig** [comment]
I've made a start at this in ffp firmware, but only arbitrary sequences, I don't yet have a TAP state machine that can do JTDP accesses. I plan to add such a thing but don't know what the timeline will be.

The ffp version is bitbanged because there's no second SPI peripheral, so the actual underlying data shifting will want to use the SPI peripheral instead in the BSP.
